### PR TITLE
NERT-577 replaced auth type from projects list view with focus, added…

### PR DESCRIPTION
**Pull request by oscar-ip**
… focus to plans list view

## Links to Jira Tickets

- NERT-577

## Description of Changes

- Non Auth projects list view replaced authorization type with focus
- Non Auth plan view added focus column
- Auth projects list view replaced authorization type with focus
- Auth plan view added focus column

### CODE REVIEW

**Review by KjartanE — COMMENTED** [review]
image
slight visual bug when only "Cultural or Community Investment Initiative" is selected

**Comment by oscar-ip** [comment]
Ok let me fix that i know where the problem is :-)

**Comment by oscar-ip** [comment]
fix in place now

**Review by popkinj — APPROVED** [review]
:+1:

**Pull request merged**
