### PR TITLE
NERT-613 extended project people involved to work with ranges

### PR DESCRIPTION
**Pull request by oscar-ip**
## Links to Jira Tickets

- NERT-613

## Description of Changes

- Project UI widget for "Number of People Involved" when creating or editing a project or draft extended to support ranges

### CODE REVIEW

**Comment by KjartanE** [comment]
image
Only comment is if we wanted to make sure this Range Field is in between the current selected numbers?
Otherwise looks great!

**Review by KjartanE — APPROVED** [review]
🐱

**Review by popkinj — APPROVED** [review]
Nice work @oscar-ip

**Comment by oscar-ip** [comment]
> Only comment is if we wanted to make sure this Range Field is in between the current selected numbers? Otherwise looks great!

we certainly could but as a first pass I think we should be good
Unless we get direct feedback from the client :-)

**Pull request merged**
