### PR TITLE
Isolating projects and plans

### PR DESCRIPTION
**Pull request by popkinj**
Screenshot from 2024-04-19 10-45-06

### CODE REVIEW

**Review by oscar-ip — DISMISSED** [review]
looks great!
Just noticed that "Project Boundary" label doesn't include plans perhaps we could rename that to "NERT Boundary" or something more appropriate

**Comment by popkinj** [comment]
> looks great! Just noticed that "Project Boundary" label doesn't include plans perhaps we could rename that to "NERT Boundary" or something more appropriate

Good thinking.

**Comment by popkinj** [comment]
Screenshot from 2024-04-19 11-03-37

**Review by oscar-ip — APPROVED** [review]
Perfect :-)

**Pull request merged**
