### PR TITLE
Nert 623 - Sidebar and Layer Enhancements

### PR DESCRIPTION
**Pull request by popkinj**
- New Sidebar within map
- Sidebar minimize is configurable
- Grouped all WMS protection layers into one
- New Seismic Line Vector Tile dataset
- Styling example of Seismic Line Layer
- Hover effect visually highlights Seismic Line feature
- Hover example tooltip of Seismic Line Layer
- Original layer switcher is in all embedded maps but contains new layers

Screenshot from 2024-09-11 15-31-07
Screenshot from 2024-09-11 15-32-02
Screenshot from 2024-09-11 15-33-06
Screenshot from 2024-09-11 15-33-35
Screenshot from 2024-09-11 15-35-46

### CODE REVIEW

**Review by oscar-ip — COMMENTED** [review]
There is an issue with the Regions boundary, after loading the map if you uncheck the checkbox the layer goes away which is good but if yo check it again the layer doesn't show any more

**Comment by popkinj** [comment]
> There is an issue with the Regions boundary, after loading the map if you uncheck the checkbox the layer goes away which is good but if yo check it again the layer doesn't show any more

ok... thanks for finding that.
Is it in the main map, embedded maps or all maps?

**Comment by oscar-ip** [comment]
> > There is an issue with the Regions boundary, after loading the map if you uncheck the checkbox the layer goes away which is good but if yo check it again the layer doesn't show any more
> 
> ok... thanks for finding that. Is it in the main map, embedded maps or all maps?

Main map, have not test yet the others

**Comment by oscar-ip** [comment]
"Protected Areas" is the parks + MKMA and should be always shown just as before (no need to have a checkbox in the side bar)

Also, not sure why this layer disappears when zooming out

**Comment by popkinj** [comment]
> "Protected Areas" is the parks + MKMA and should be always shown just as before (no need to have a checkbox in the side bar)
> 
> Also, not sure why this layer disappears when zooming out

All layers have a min or max zoom.... You can adjust the default and possible allow users to change that.

**Comment by oscar-ip** [comment]
"Region Boundaries" should be "Natural Resource Mgmt. Regions"
it is pretty long but perhaps can be displayed in 2 lines

**Comment by popkinj** [comment]
> Yeah... was thinking a lot about that one. I was planning to pitch a shorter version.... and we could adjust it to selected Regions in the embedded maps.

FYI I already discuss this with Morgan, and tried to get it shorter, she decided on what is in the previous comment

**Comment by oscar-ip** [comment]
I don't see the Info buttons in the layers menu options, I assume that is coming

**Comment by popkinj** [comment]
> I don't see the Info buttons in the layers menu options, I assume that is coming

Yes... that's coming.

**Comment by oscar-ip** [comment]
> > "Protected Areas" is the parks + MKMA and should be always shown just as before (no need to have a checkbox in the side bar)
> > Also, not sure why this layer disappears when zooming out
> 
> All layers have a min or max zoom.... You can adjust the default and possible allow users to change that.

Ok that makes sense now :-)

**Comment by popkinj** [comment]
> > Yeah... was thinking a lot about that one. I was planning to pitch a shorter version.... and we could adjust it to selected Regions in the embedded maps.
> 
> FYI I already discuss this with Morgan, and tried to get it shorter, she decided on what is in the previous comment

Got it. I'll change it and we can discuss in the meeting tomorrow.

**Comment by popkinj** [comment]
> There is an issue with the Regions boundary, after loading the map if you uncheck the checkbox the layer goes away which is good but if yo check it again the layer doesn't show any more

I wasn't able to replicate. Could you please send me what's in the console when you next see this?

**Comment by popkinj** [comment]
> "Region Boundaries" should be "Natural Resource Mgmt. Regions" it is pretty long but perhaps can be displayed in 2 lines

Done.

**Comment by popkinj** [comment]
> "Protected Areas" is the parks + MKMA and should be always shown just as before (no need to have a checkbox in the side bar)
> 
> Also, not sure why this layer disappears when zooming out

Done... Commented the layer switcher entry out as we will discuss further in today's meeting.

**Comment by popkinj** [comment]
Screenshot from 2024-09-12 10-20-47

**Comment by oscar-ip** [comment]
> > There is an issue with the Regions boundary, after loading the map if you uncheck the checkbox the layer goes away which is good but if yo check it again the layer doesn't show any more
> 
> I wasn't able to replicate. Could you please send me what's in the console when you next see this?

The regions toggle now works, I think you resolved that in yesterdays latest commits :-) 

But there are still a bunch of errors in the console log every time you toggle the regions, you can take a look https://restoration-tracker-app-201-d83219-dev.apps.silver.devops.gov.bc.ca/
here is a screenshot
ConsoleLog201

**Comment by oscar-ip** [comment]
Another thing regarding the MKMA, can you display the legend as described in the jira item:
Add the MKMA layer to the existing default parks layer with the legend "Muskwa-Kechika Management Area"
The parks have the legend already so that is good

**Comment by popkinj** [comment]
> Another thing regarding the MKMA, can you display the legend as described in the jira item: Add the MKMA layer to the existing default parks layer with the legend "Muskwa-Kechika Management Area" The parks have the legend already so that is good

Maybe we should chat about this. I understood that the parks and MKMA are on by default.... aka. Not in the layer picker and part of the basemap. A previous iteration I had it just like you mentioned.... part of the protected areas and in the layer picker. The dropdown with symbology was something yet to come.

**Comment by popkinj** [comment]
> > > There is an issue with the Regions boundary, after loading the map if you uncheck the checkbox the layer goes away which is good but if yo check it again the layer doesn't show any more
> > 
> > 
> > I wasn't able to replicate. Could you please send me what's in the console when you next see this?
> 
> The regions toggle now works, I think you resolved that in yesterdays latest commits :-)
> 
> But there are still a bunch of errors in the console log every time you toggle the regions, you can take a look https://restoration-tracker-app-201-d83219-dev.apps.silver.devops.gov.bc.ca/ here is a screenshot ConsoleLog201

Those errors are part of Maplibre. Kinda annoying I know.
It's requesting vector tiles that don't exist.... Usually because there's no data for those tiles.

**Review by oscar-ip — APPROVED** [review]
good stuff, we now have a sidebar but lots of changes still to come on this

**Pull request merged**
