### PR TITLE
NERT-661: Add pi warning and formik error popup to edit project/plan

### PR DESCRIPTION
**Pull request by KjartanE**
## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-661

## Description of Changes

- {List all relevant code changes. Include any changes to the business workflow that might not be obvious to the reviewers of this PR.}

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

### CODE REVIEW

**Comment by oscar-ip** [comment]
I was able to save a plan with no "Plan Focus", no formik error popup
I think this is not related to the PR, it is a bug that was there already

**Comment by KjartanE** [comment]
> I was able to save a plan with no "Plan Focus", no formik error popup I think this is not related to the PR, it is a bug that was there already

Can fix this if wanted!

**Comment by oscar-ip** [comment]
> > I was able to save a plan with no "Plan Focus", no formik error popup I think this is not related to the PR, it is a bug that was there already
> 
> Can fix this if wanted!

Yes, please 
 :-)

**Review by oscar-ip — APPROVED** [review]
Good stuff, thanks ! :-)

**Pull request merged**
