### PR TITLE
NERT-564: Thumbnail not accessible to the public map.

### PR DESCRIPTION
**Pull request by KjartanE**
## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-564

## Description of Changes

- update thumbnail get request to point at public endpoint

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

### CODE REVIEW

**Review by oscar-ip — COMMENTED** [review]
still seeing that the public map is not loading the thumbnail when testing on the PR 152 in dev

**Comment by KjartanE** [comment]
> still seeing that the public map is not loading the thumbnail when testing on the PR 152 in dev

image

**Comment by popkinj** [comment]
> still seeing that the public map is not loading the thumbnail when testing on the PR 152 in dev

Yeah... I'm also getting the permission redirect thing.

Screenshot from 2024-08-01 13-27-31

**Comment by KjartanE** [comment]
> > still seeing that the public map is not loading the thumbnail when testing on the PR 152 in dev
> 
> Yeah... I'm also getting the permission redirect thing.
> 
> Screenshot from 2024-08-01 13-27-31

Seems to be an issue of the Map Container not updating properly from my push. I dropped the pod and rebuilding

**Comment by oscar-ip** [comment]
> > > still seeing that the public map is not loading the thumbnail when testing on the PR 152 in dev
> > 
> > 
> > Yeah... I'm also getting the permission redirect thing.
> > Screenshot from 2024-08-01 13-27-31
> 
> Seems to be an issue of the Map Container not updating properly from my push. I dropped the pod and rebuilding

I just tested and it is working now :-)

**Review by oscar-ip — APPROVED** [review]
great it is working now :-)

**Pull request merged**
