### PR TITLE
NERT-656: Hide conservation area names when creating/editing/viewing project

### PR DESCRIPTION
**Pull request by KjartanE**
## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-656
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-657
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-658
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-659
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-660

## Description of Changes

- Project Create add question to hide or not conservation areas
- Project Edit add question to hide or not conservation areas 
- Project View hide conservation area names when not public
- API and Data model changes to support hiding conservation areas

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

### CODE REVIEW

**Comment by oscar-ip** [comment]
Testing on the PR, looks like the project view is no longer displaying the conservation areas, see Project-Creator-Z9
Edit this project change the conservation area to Yes and save, it is always saving "No".

**Comment by KjartanE** [comment]
> Testing on the PR, looks like the project view is no longer displaying the conservation areas, see Project-Creator-Z9 Edit this project change the conservation area to Yes and save, it is always saving "No".

This is due to no location being saved within the project. This is a side issue/bug that is noticeable now when we are interacting with the component more. We can look to saving Conservation areas separately from the location information. 
I guess the question is, can there be an overlapping conservation area with no location set?

**Comment by oscar-ip** [comment]
> > Testing on the PR, looks like the project view is no longer displaying the conservation areas, see Project-Creator-Z9 Edit this project change the conservation area to Yes and save, it is always saving "No".
> 
> This is due to no location being saved within the project. This is a side issue/bug that is noticeable now when we are interacting with the component more. We can look to saving Conservation areas separately from the location information. I guess the question is, can there be an overlapping conservation area with no location set?

I would say yes, you could have a case where they do know the conservation areas but they don't have a geojson

**Review by oscar-ip — APPROVED** [review]
Good stuff! :-)

**Pull request merged**
