### PR TITLE
NERT-32: Manage Project

### PR DESCRIPTION
**Pull request by KjartanE**
## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-413
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-414
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-415
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-416
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-417
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-418
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-419
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-420
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-421
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-422
- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-331

## Description of Changes

- Manage project, Edit page
- Get data for edit page
- Submit edits
- Handle input errors
- handle routing
- isPublic, authorization, partnership, funding

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

### CODE REVIEW

**Review by popkinj — DISMISSED** [review]
Good job @KjartanE

**Review by popkinj — DISMISSED** [review]
Need me some of these fixes :smile:

**Review by oscar-ip — APPROVED** [review]
👋

**Comment by popkinj** [comment]
:tada:

**Pull request merged**
