### PR TITLE
Nert 558 - Sensitive areas are replaced with a mask for unauthorized users.

### PR DESCRIPTION
**Pull request by popkinj**
- Common masking component to convert features into larger circle shapes that encompass the original
- Masks displayed for all public users.
- Masks displayed on all view pages public and non-public.
- Both mask and original shape showing if the user has access to edit the geometry
- Masks displayed feature by feature basis, for example: This image illustrates that the users has specified one feature to be masked and one not to be.

Screenshot from 2024-07-31 14-37-02

### CODE REVIEW

**Comment by oscar-ip** [comment]
I can see the original features in the public map along with the masks :-(
image

**Comment by popkinj** [comment]
> I can see the original features in the public map along with the masks :-( image

Can you send me the geojson file you're testing with?

Update - Never mind. I'll grab it from the PR app.

**Comment by popkinj** [comment]
I see what's happening. The original shapes aren't drawing... If you zoom in you'll see there are masked.... However, the masks are being masked again haha. Thanks for finding that @oscar-ip

**Comment by oscar-ip** [comment]
Sounds good, let me know when you need me to test again

**Comment by popkinj** [comment]
I believe things are behaving as expected now. You can see here, the smaller shapes were masked. The big one was left as is.
Screenshot from 2024-08-02 13-24-25
Screenshot from 2024-08-02 13-30-30

**Review by oscar-ip — APPROVED** [review]
Good stuff! 👍 
I tested in the PR

**Pull request merged**
