### PR TITLE
Nert 615 - Printing and PDF Support

### PR DESCRIPTION
**Pull request by popkinj**
**What's New**
- Custom styling to pages being printed
- Utilizing browser built-in printing and PDF generation support
- Tested in Chrome and Firefox
- Updated Maplibre from 4.5.x to 4.7.x
- Configured region layer to scale features even if the zoom level doesn't exist

**Landing Page BEFORE Print Styling**
main-map-before

**Landing Page AFTER Print Styling**
Screenshot from 2024-10-08 14-34-42

**Details Page BEFORE Print Styling**
view-project-before

**Details Page AFTER Print Styling**
Screenshot from 2024-10-08 14-35-29

### CODE REVIEW

**Comment by oscar-ip** [comment]
looks like this is all the browser printing, which as we discussed, always a pain when it comes to proper paging and browser support.
What about the Print button PDF printing? you can see it when you open a project or plan this one was supposed to generate a client side PDF. 
image

**Comment by popkinj** [comment]
> looks like this is all the browser printing, which as we discussed, always a pain when it comes to proper paging and browser support. What about the Print button PDF printing? you can see it when you open a project or plan this one was supposed to generate a client side PDF. image

Thanks for testing @oscar-ip 
Is this a screen shot of the PDF?

I probably should have added a testing workflow to the PR docs.
When in any of the pages, go to File-> Print. Or hit CTRL-P. This SHOULD get us to where we agreed was how we're utilising the browsers natural ability to print or create a PDF.

**Comment by oscar-ip** [comment]
> > looks like this is all the browser printing, which as we discussed, always a pain when it comes to proper paging and browser support. What about the Print button PDF printing? you can see it when you open a project or plan this one was supposed to generate a client side PDF. image
> 
> Thanks for testing @oscar-ip Is this a screen shot of the PDF?
> 
> I probably should have added a testing workflow to the PR docs. When in any of the pages, go to File-> Print. Or hit CTRL-P. This SHOULD get us to where we agreed was how we're utilising the browsers natural ability to print or create a PDF.

Not a screenshot of the PDF, it is a screenshot of our UI we had a specific function to generate a PDF to avoid the browser printing issues. Take a look at react-to-pdf package. 
The Browser printing is a nice to have, in any case lets talk about it tomorrow.

I am approving this PR as it doesn't hurt to have it.

**Review by oscar-ip — APPROVED** [review]
see comments :-)

**Comment by popkinj** [comment]
> > > looks like this is all the browser printing, which as we discussed, always a pain when it comes to proper paging and browser support. What about the Print button PDF printing? you can see it when you open a project or plan this one was supposed to generate a client side PDF. image
> > 
> > 
> > Thanks for testing @oscar-ip Is this a screen shot of the PDF?
> > I probably should have added a testing workflow to the PR docs. When in any of the pages, go to File-> Print. Or hit CTRL-P. This SHOULD get us to where we agreed was how we're utilising the browsers natural ability to print or create a PDF.
> 
> Not a screenshot of the PDF, it is a screenshot of our UI we had a specific function to generate a PDF to avoid the browser printing issues. Take a look at react-to-pdf package. The Browser printing is a nice to have, in any case lets talk about it tomorrow.
> 
> I am approving this PR as it doesn't hurt to have it.

Correct. This is all browser side. It's definitely the skate board before the bike.

Yes... we can chat today.

**Pull request merged**
