### PR TITLE
NERT-427: Focus species, move from ES to IDIS

### PR DESCRIPTION
**Pull request by KjartanE**
## Links to Jira Tickets

- https://apps.nrs.gov.bc.ca/int/jira/browse/NERT-427?

## Description of Changes

- update taxon to ITIS TSN
- fix routes and remove old code
- update UI for general information

## Testing Notes

- {List any relevant testing considerations, necessary pre-reqs, and areas of the app to focus on. Specifically, include anything that will help the reviewers of this PR verify the code is functioning as expected.}

### CODE REVIEW

**Comment by oscar-ip** [comment]
Testing on the PR Public API needs adjusting
GET https://restoration-tracker-api-155-d83219-dev.apps.silver.devops.gov.bc.ca/api/public/projects 500 (Internal Server Error)
{
    "name": "Internal Server Error",
    "status": 500,
    "message": "Invalid response for status code 200",
    "errors": [
        {
            "instancePath": "/response/0/species",
            "schemaPath": "#/properties/response/items/properties/species/required",
            "keyword": "required",
            "params": {
                "missingProperty": "focal_species_names"
            },
            "message": "must have required property 'focal_species_names'"
        }, .....

**Comment by oscar-ip** [comment]
When creating/editing Focal Species is not a required field
When entering any letter on the input there are no matches found
useTaxonomyApi.ts:42 
      
        
       GET https://restoration-tracker-app-155-d83219-dev.apps.silver.devops.gov.bc.ca/?terms%5B0%5D=d 503 (Service Unavailable)

**Comment by KjartanE** [comment]
> Testing on the PR Public API needs adjusting GET https://restoration-tracker-api-155-d83219-dev.apps.silver.devops.gov.bc.ca/api/public/projects 500 (Internal Server Error) { "name": "Internal Server Error", "status": 500, "message": "Invalid response for status code 200", "errors": [ { "instancePath": "/response/0/species", "schemaPath": "#/properties/response/items/properties/species/required", "keyword": "required", "params": { "missingProperty": "focal_species_names" }, "message": "must have required property 'focal_species_names'" }, .....

Fixxed

**Comment by KjartanE** [comment]
> When creating/editing Focal Species is not a required field When entering any letter on the input there are no matches found useTaxonomyApi.ts:42
> 
> ```
>    GET https://restoration-tracker-app-155-d83219-dev.apps.silver.devops.gov.bc.ca/?terms%5B0%5D=d 503 (Service Unavailable)
> ```

Removed required, seeming to be a network policy issue on PR instance. Working on creating policy

**Review by oscar-ip — APPROVED** [review]
Nice work 👍

**Pull request merged**
